//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventActivity
    {
        public int EventId { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public Nullable<int> EventLevel { get; set; }
        public string ExceptionData { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string DataBlock { get; set; }
    }
}
